### ISSUE TITLE
About direction module

### ISSUE THREAD

**Issue by cswwp** [ggsDing/ResDec#1]
Thank you for sharing nice repo. I am trying to reproduce the result, and struggle in direction layer, and i test one label image with the DirectionNet which is a binary gray image(0 is the background, 1 is the road), but the out put direction map seems not normal, do you mind help me to seek the reason? thank you, as follow is the output direction map with the DirectionNet
![image](https://user-images.githubusercontent.com/11901683/99937186-03ff1c80-2da0-11eb-88cf-b617bddd618f.png)

**Comment by DingLei14** [comment]
I am not sure about the problem. You can try a different 'rwidth' parameter or add a '#' at line 98 in 'DirectionNet' and see the output.

**Comment by cswwp** [comment]
> I am not sure about the problem. You can try a different 'rwidth' parameter or add a '#' at line 98 in 'DirectionNet' and see the output.

@ggsDing It works when i comment the reduce_direction method in forward, and the visualize result as follows:
![image](https://user-images.githubusercontent.com/11901683/99975480-409d3900-2ddd-11eb-9d09-6659dba79f10.png)
and it seems some road direction are not complete but the GT is complete, do you have any suggestion, and now my param is DirectionNet(rwidth=15, range_detect=21).to('cuda'), thanks again

**Comment by DingLei14** [comment]
From your image, there're values on the road regions.
you can try the following codes to visualize the directions:

`
DIRECTION_COLOR_12 = {0:[0,0,0],1:[255,0,0],2:[255,0,125],3:[255,0,255],4:[125,0,255],5:[0,0,255],6:[0,125,255],7:[0,255,255],8:[0,255,125],9:[0,255,0],10:[125,255,0],11:[255,255,0],12:[255,125,0],13:[255,255,255]}

DIRECTION_COLOR_4 = {0:[0,0,0],1:[255,0,0],2:[0,0,255],3:[0,255,0],4:[255,255,0],5:[255,255,255]}

def direction_index2color(direction):
    h, w = direction.shape
    color_map = np.zeros([h, w, 3])
    for j in range(h):
        for i in range(w):
            color_map[j,i,:] = DIRECTION_COLOR_4[direction[j,i]]
    return color_map.astype(np.uint8)

direction_map = direction_map*label_bn #mask road regions
direction_color = direction_index2color(direction_map)
`
the direction colors are self-defined and you can add more colors.

**Comment by cswwp** [comment]
> From your image, there're values on the road regions.
> you can try the following codes to visualize the directions:
> 
> `
> DIRECTION_COLOR_13 = {0:[0,0,0],1:[255,0,0],2:[255,0,125],3:[255,0,255],4:[125,0,255],5:[0,0,255],6:[0,125,255],7:[0,255,255],8:[0,255,125],9:[0,255,0],10:[125,255,0],11:[255,255,0],12:[255,125,0],13:[255,255,255]}
> 
> DIRECTION_COLOR_4 = {0:[0,0,0],1:[255,0,0],2:[0,0,255],3:[0,255,0],4:[255,255,0],5:[255,255,255]}
> 
> def direction_index2color(direction):
> h, w = direction.shape
> color_map = np.zeros([h, w, 3])
> for j in range(h):
> for i in range(w):
> color_map[j,i,:] = RS.DIRECTION_COLOR_4[direction[j,i]]
> return color_map.astype(np.uint8)
> 
> direction_map = direction_map*label_bn #mask road regions
> direction = direction_index2color(direction_map)
> `

Awesome, Thank you
